name: "on push release"

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PROJECT_PATH: Wyoming.Net.Satellite.App.Maui/Wyoming.Net.Satellite.App.Maui.csproj
      MauiVersion: 9.0.120

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.x
          
      - name: Install MAUI Workload
        run: dotnet workload install maui

      - name: Set version variables
        run: |
          $buildNumber = "${{ github.run_number }}"
          echo "VERSION_DISPLAY=1.0.$buildNumber" >> $env:GITHUB_ENV
          echo "VERSION_CODE=$((10000 + $buildNumber))" >> $env:GITHUB_ENV

      - name: Restore NuGet packages
        run: dotnet restore "$env:PROJECT_PATH"

      - name: Build (Release)
        run: |
          dotnet build "$env:PROJECT_PATH" -f net9.0-android -c Release \
            -p:ApplicationVersion="0.1" \
            -p:ApplicationDisplayVersion="0.1" \
            -p:AndroidSigningKeyAlias="myapp" \
            -p:AndroidSigningKeyPass="${{ secrets.password }}" \
            -p:AndroidSigningStorePass="${{ secrets.password }}" \
            -p:AndroidSigningStore="myapp.keystore" \
            -p:AndroidBuildApplicationPackage=true \
            -p:AndroidPackageFormat="apk"

      - name: debug
        run: find ..

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          automatic_release_tag: "latest"
          files: "**.apk"
